# Generated by Django 2.2.2 on 2019-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_words',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='words_count',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
