# Generated by Django 2.2.2 on 2019-06-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_orderletters_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='traningword',
            name='base_word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Word'),
        ),
        migrations.AddField(
            model_name='traningword',
            name='last_letter',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='traningword',
            name='last_letter_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='traningword',
            name='order_letters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.OrderLetters'),
        ),
    ]
