# Generated by Django 2.2.2 on 2019-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20190615_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderletters',
            name='current_letter',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='orderletters',
            name='current_letter_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
