# Generated by Django 2.2.2 on 2019-06-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20190615_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderletters',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
