# Generated by Django 2.2.2 on 2019-06-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_orderletters_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='slug',
        ),
    ]
